### PR TITLE
Bug fix/undefined winner

### LINKED ISSUE #44: This weeks winner - undefined
Bug - this weeks winner amount of steps in coming up undefined

### PR DESCRIPTION
**Pull request by ttarlov**
## Type of change made:
 - [x] Bugfix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] Styling- no new features

## Detailed Description

Why is this change required?

     - Bug Fix

What problem does it solve?

    - Bug fixes undefined value for This Weeks Winner Section. 
    - Creates conditional logic to fix the issue. 
    - closes #44 issue

Files modified:
 - [ ] index.html
 - [ ] styles.scss
 - [ ] base.scss
 - [x] scripts.js
 - [ ] User.js
 - [ ] User-repo.js
 - [x] Activity.js
 - [ ] Hydration.js
 - [ ] Sleep.js

### CODE REVIEW

File: src/Activity.js [hunk 1]
```diff
@@ -76,7 +76,10 @@ class Activity {
   showcaseWinner(user, date, userRepo) {
     let namedList = this.showChallengeListAndWinner(user, date, userRepo);
     let winner = this.showChallengeListAndWinner(user, date, userRepo).shift();
-    return winner;
+    if(winner == undefined) {
+      return "No Winner This Week"
+    }
+    return `${winner} steps`;
```
Comment (carflor) [inline src/Activity.js:82]: Great default conditional.
